function cameraParams = cb_cab_r(fps) 
    
    % Define images to process
    if fps == 120
       imageFileNames = {
        './Calibration/R/14.png',...
        './Calibration/R/13.png',...
        './Calibration/R/12.png',...
        './Calibration/R/11.png',...
        './Calibration/R/10.png',...
        './Calibration/R/9.png',...
        './Calibration/R/8.png',...
        './Calibration/R/7.png',...
        './Calibration/R/6.png',...
        './Calibration/R/5.png',...
        './Calibration/R/3.png',...
        './Calibration/R/4.png',...
        './Calibration/R/2.png',...
        './Calibration/R/1.png',...
        };
    elseif fps == 121
       imageFileNames = {'./Calibration/M/15.png',...
         './Calibration/M/13.png',...
        './Calibration/M/12.png',...
        './Calibration/M/11.png',...
        './Calibration/M/10.png',...
        './Calibration/M/9.png',...
        './Calibration/M/8.png',...
        './Calibration/M/7.png',...
        './Calibration/M/6.png',...
        './Calibration/M/5.png',...
        './Calibration/M/4.png',...
        './Calibration/M/3.png',...
        './Calibration/M/2.png',...
        './Calibration/M/1.png',...
    };
   else
       imageFileNames = {
        './Calibration/R-60/11.png',...
        './Calibration/R-60/10.png',...
        './Calibration/R-60/9.png',...
        './Calibration/R-60/8.png',...
        './Calibration/R-60/7.png',...
        './Calibration/R-60/6.png',...
        './Calibration/R-60/5.png',...
        './Calibration/R-60/3.png',...
        './Calibration/R-60/4.png',...
        './Calibration/R-60/2.png',...
        './Calibration/R-60/1.png',...
        };
    end
        % Detect checkerboards in images
    [imagePoints, boardSize, imagesUsed] = detectCheckerboardPoints(imageFileNames);
    imageFileNames = imageFileNames(imagesUsed);

    % Read the first image to obtain image size
    originalImage = imread(imageFileNames{1});
    [mrows, ncols, ~] = size(originalImage);

    % Generate world coordinates of the corners of the squares
    squareSize = 23;  % in units of 'millimeters'
    worldPoints = generateCheckerboardPoints(boardSize, squareSize);

    % Calibrate the camera
    [cameraParams, imagesUsed, estimationErrors] = estimateCameraParameters(imagePoints, worldPoints, ...
        'EstimateSkew', false, 'EstimateTangentialDistortion', false, ...
        'NumRadialDistortionCoefficients', 2, 'WorldUnits', 'millimeters', ...
        'InitialIntrinsicMatrix', [], 'InitialRadialDistortion', [], ...
        'ImageSize', [mrows, ncols]);

    % Visualize pattern locations
    %h2=figure; showExtrinsics(cameraParams, 'CameraCentric');

    % Display parameter estimation errors
    displayErrors(estimationErrors, cameraParams);

end

